// Client directory: the master client list (client name.xlsx, June–Sept) grouped
// into brands, plus the resolver that maps the free-text "center name" /
// "hospital clinic name" typed into the sheets onto a brand and, where the row
// says enough, a specific branch. Generated by tools/client_directory/build.py —
// edit the rules / aliases there and rebuild rather than editing this file.
(function(global){
const BRANCHES=/*BRANCHES*/[];
// Sheet spellings that can't be derived from the master names: [brand, [raw names…], optional location RegExp source].
const ALIASES=/*ALIASES*/[];
// Different clinics whose names sit one typo away from a listed client; never fuzzy-match these.
const NOT_LISTED_NAMES=/*NOT_LISTED*/[];

const STOP=new Set(['THE','DR','AND','A','UNIT','AUNIT','UNITE','OF','PVT','PRIVATE','LTD','LIMITED','LIMITE','LMT','LLP','P','CENTRE','CENTER','CENTR','CENRE','CNETRE','CETRE','CLINIC','CLIINC','HOSPITAL','HOSPTAL','OSPITAL','HOSPITALS','IVF','IV','IVCF','INFERTILITY','NURSING','NURSHING','HOME','RESEARCH','REASEARCH','RESEARH','INSTITUTE','BY']);
function lev(a,b){if(a===b)return 0;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(prev[j]+1,cur[j-1]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}return prev[b.length]}
function clientTokens(s){return String(s||'').toUpperCase().replace(/[’`]/g,"'").replace(/&/g,' AND ').replace(/'S\b/g,'S').replace(/'/g,'').replace(/[^A-Z0-9]+/g,' ').trim().split(' ').filter(t=>t&&t!=='S'&&!STOP.has(t)&&!(t.length>=7&&lev(t,'FERTILITY')<=2)).map(t=>t.length>4&&t.endsWith('S')?t.slice(0,-1):t)}
const compact=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
function branchBase(name){let n=name.replace(/\((NOVA IVF|MOTHERHOOD|MH)\)/g,'').replace(/\(\s*A\s*UNIT[^)]*\)?/gi,'').replace(/[\s)]+$/,'');const m=n.match(/^(.*\S)\s*-\s*([^-]+?)\s*$/);return m&&!/\b(LTD|LIMITED|LLP)\b/.test(m[2])?m[1]:n}

// key (space-joined tokens) -> brand
const keyBrand=new Map(),exactName=new Map(),brandBranches=new Map();
const addKey=(k,brand)=>{if(k&&!keyBrand.has(k))keyBrand.set(k,brand)};
for(const b of BRANCHES){exactName.set(compact(b.name),b);if(!brandBranches.has(b.brand))brandBranches.set(b.brand,[]);brandBranches.get(b.brand).push(b)}
for(const b of BRANCHES){addKey(clientTokens(b.brand).join(' '),b.brand);addKey(clientTokens(branchBase(b.name)).join(' '),b.brand)}
const locAliases=[];
for(const [brand,names,loc] of ALIASES){if(loc){locAliases.push({brand,keys:new Set(names.map(n=>clientTokens(n).join(' '))),loc:new RegExp(loc,'i')});continue}names.forEach(n=>addKey(clientTokens(n).join(' '),brand))}
const NOT_LISTED=new Set(NOT_LISTED_NAMES.map(n=>clientTokens(n).join(' ')));
const keys=[...keyBrand.keys()],keyCompact=new Map(keys.map(k=>[compact(k),k]));

function brandFromText(s,location){
 const toks=clientTokens(s),k=toks.join(' ');if(!k||NOT_LISTED.has(k))return'';
 for(const a of locAliases)if(a.keys.has(k)&&a.loc.test(location||''))return a.brand;
 if(keyBrand.has(k))return keyBrand.get(k);
 const c=compact(k);if(keyCompact.has(c))return keyBrand.get(keyCompact.get(c));
 // Known key followed by extra words (location, "Fertility & IVF", branch): take the longest such key.
 let best='',bestLen=0;for(const key of keys){const kt=key.split(' ');if(kt.length<=toks.length&&kt.length>bestLen&&kt.every((t,i)=>t===toks[i])&&(kt.length>1||kt[0].length>=4)){best=key;bestLen=kt.length}}
 if(best)return keyBrand.get(best);
 // A truncated name ("DESTINY IVF") that is the start of exactly one brand's key.
 if(toks[0].length>=4){const hits=new Set();for(const key of keys){const kt=key.split(' ');if(toks.length<kt.length&&toks.every((t,i)=>t===kt[i]))hits.add(keyBrand.get(key))}if(hits.size===1)return[...hits][0]}
 // Close misspelling of a whole key (same first letter, so "NORVIC" never becomes "ORIGIN").
 let fz='',fd=99,tie=false;for(const [ck,key] of keyCompact){const L=Math.max(ck.length,c.length);if(ck[0]!==c[0]||Math.abs(ck.length-c.length)>2||L<5)continue;const d=lev(ck,c),lim=L<=7?1:L<=14?2:3;if(d<=lim){if(d<fd){fd=d;fz=key;tie=false}else if(d===fd&&keyBrand.get(key)!==keyBrand.get(fz))tie=true}}
 if(fz&&!tie)return keyBrand.get(fz);
 return'';
}
function pickBranch(brand,location,allowOnly=true){
 const list=brandBranches.get(brand)||[];if(allowOnly&&list.length===1)return list[0];
 const lt=compact(location);if(!lt)return null;
 const hits=list.filter(b=>{const bl=compact(b.branch);return bl&&(lt.includes(bl)||bl.includes(lt)||(bl.length>=5&&lev(bl,lt)<=2))});
 return hits.length===1?hits[0]:null;
}
// → {brand, branch (master entry or null), listed} or null when nothing in the directory matches.
function resolveClient(centerName,hospitalName,location){
 const hc=compact(hospitalName);
 if(hc&&exactName.has(hc)){const b=exactName.get(hc);return{brand:b.brand,branch:b,listed:true}}
 let brand='';
 if(hospitalName){brand=brandFromText(hospitalName,location);if(brand){const exact=[...(brandBranches.get(brand)||[])].find(b=>lev(compact(b.name),hc)<=3);if(exact)return{brand,branch:exact,listed:true}}}
 const namedOther=!!brand;if(!brand)brand=brandFromText(centerName,location);
 if(!brand)return null;
 // A clinic name that names an unlisted branch (e.g. a new city) must not fall back to the brand's only listed branch.
 return{brand,branch:pickBranch(brand,location,!namedOther),listed:brandBranches.has(brand)};
}
function clientDirectory(){return[...brandBranches].map(([brand,branches])=>({brand,branches}))}
global.resolveClient=resolveClient;global.clientDirectory=clientDirectory;
if(typeof module!=='undefined')module.exports={resolveClient,clientDirectory,clientTokens};
})(typeof window!=='undefined'?window:globalThis);
